### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "firstName": "Anurag",
  "lastName": "Sharma",
  "email": "anurag.user@example.com",
  "password": "User@12345",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "test@example.com",
  "password": "test",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### User Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "anurag.user@example.com",
  "password": "User@12345"
}



### Read articles of all authors by User
GET http://localhost:4000/user-api/articles


### Add comment to an article
PUT http://localhost:4000/user-api/articles
Content-Type: application/json

{
  "user":"6989799b7013502767d3f82b",
  "articleId":"6989750220ce5bf826ec4f7e",
  "comment":"good article"
 
}



###
GET http://localhost:4000/common-api/logout


###
{
  "message": "secretOrPrivateKey must have a value",
  "status": 400,
  "stack": "Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (C:\\Users\\polas\\OneDrive\\Desktop\\mern\\UserArtical-App\\blog-backend\\node_modules\\jsonwebtoken\\sign.js:111:20)\n    at authenticate (file:///C:/Users/polas/OneDrive/Desktop/mern/UserArtical-App/blog-backend/services/authService.js:51:21)\n    at async file:///C:/Users/polas/OneDrive/Desktop/mern/UserArtical-App/blog-backend/APIs/CommonAPI.js:12:25"
}